version: '3.8'

services:
  mysql:
    image: mysql:8.0
    container_name: netflix-mysql
    restart: always
    ports:
      - '3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: admin
      TZ: Asia/Seoul
    volumes:
      - ./db/mysql/data:/var/lib/mysql
      - ./db/mysql/init:/docker-entrypoint-initdb.d
  redis:
    command: redis-server
    image: redis:alpine
    restart: always
    container_name: netflix-redis
    hostname: redis
    ports:
      - 6379:6379